// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/zh-CN/about") };
import SiteFooter from "@/components/locales/zh-CN/SiteFooter";
import SiteHeader from "@/components/locales/zh-CN/SiteHeader";
export default function AboutPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u5173\u4E8EPC FIX "}</h1>

          <div className="mt-6 space-y-6 text-sm leading-7 text-slate-600 sm:text-base">
            <p>{" PC FIX \u662F\u4E00\u4E2A\u6545\u969C\u6392\u9664\u6307\u5357\uFF0C\u65E8\u5728\u5E2E\u52A9\u4EFB\u4F55\u4EBA\u8F7B\u677E\u89E3\u51B3\u4F7F\u7528\u8BA1\u7B97\u673A\u65F6\u51FA\u73B0\u7684\u5404\u79CD\u95EE\u9898\u3002 "}</p>

            <p>{" \u5F53\u60A8\u5C1D\u8BD5\u641C\u7D22\u8BA1\u7B97\u673A\u95EE\u9898\u65F6\uFF0C\u60A8\u7ECF\u5E38\u4F1A\u9047\u5230\u6280\u672F\u672F\u8BED\u6216\u590D\u6742\u7684\u89E3\u91CA\u3002 PC FIX \u7684\u7ED3\u6784\u662F\u6839\u636E\u7528\u6237\u5B9E\u9645\u9047\u5230\u7684\u75C7\u72B6\u6765\u67E5\u627E\u95EE\u9898\u3002 "}</p>

            <p>{" \u5728\u53EF\u80FD\u7684\u60C5\u51B5\u4E0B\uFF0C\u89E3\u51B3\u65B9\u6848\u5C06\u4ECE\u6700\u7B80\u5355\u4E14\u6210\u672C\u6700\u4F4E\u7684\u65B9\u6CD5\u5F00\u59CB\u7EC4\u7EC7\uFF0C\u7136\u540E\u9010\u6B65\u8FDB\u884C\u66F4\u9AD8\u7EA7\u7684\u6B65\u9AA4\u3002 "}</p>

            <p>{" \u7531\u4E8E\u6BCF\u4E2A\u8BA1\u7B97\u673A\u73AF\u5883\u53EF\u80FD\u4E0D\u540C\uFF0C\u6240\u63D0\u4F9B\u7684\u65B9\u6CD5\u5E76\u4E0D\u80FD\u4FDD\u8BC1\u5728\u6240\u6709\u60C5\u51B5\u4E0B\u5F97\u5230\u76F8\u540C\u7684\u7ED3\u679C\u3002\u5982\u679C\u60A8\u6709\u91CD\u8981\u6570\u636E\uFF0C\u6211\u4EEC\u5EFA\u8BAE\u60A8\u5148\u8FDB\u884C\u5907\u4EFD\uFF0C\u5982\u679C\u6000\u7591\u5B58\u5728\u7269\u7406\u6545\u969C\uFF0C\u8BF7\u63A5\u53D7\u4E13\u4E1A\u68C0\u67E5\u3002 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
