// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/ja/contact") };
import SiteFooter from "@/components/locales/ja/SiteFooter";
import SiteHeader from "@/components/locales/ja/SiteHeader";
export default function ContactPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u304A\u554F\u3044\u5408\u308F\u305B "}</h1>

          <p className="mt-6 leading-7 text-slate-600">{" PC FIX\u306E\u5185\u5BB9\u30A8\u30E9\u30FC\u3001\u4FEE\u6B63\u8981\u6C42\u3001\u63D0\u643A\u306A\u3069\u306E\u304A\u554F\u3044\u5408\u308F\u305B\u306E\u305F\u3081\u306E\u30DA\u30FC\u30B8\u3067\u3059\u3002 "}</p>

          <div className="mt-8 rounded-xl bg-slate-50 p-5">
            <h2 className="font-bold text-slate-950">{" \u304A\u554F\u3044\u5408\u308F\u305B\u65B9\u6CD5 "}</h2>

            <p className="mt-2 text-sm leading-6 text-slate-500">{" \u304A\u554F\u3044\u5408\u308F\u305B\u306F\u4E0B\u8A18\u30E1\u30FC\u30EB\u30A2\u30C9\u30EC\u30B9\u307E\u3067\u304A\u9001\u308A\u304F\u3060\u3055\u3044\u3002 "}</p>

            <a href="mailto:contact@pcfixbase.com" className="mt-3 inline-block font-semibold text-blue-600 hover:underline">
              contact@pcfixbase.com
            </a>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
