// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/en/about") };
import SiteFooter from "@/components/locales/en/SiteFooter";
import SiteHeader from "@/components/locales/en/SiteHeader";
export default function AboutPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" About PC FIX "}</h1>

          <div className="mt-6 space-y-6 text-sm leading-7 text-slate-600 sm:text-base">
            <p>{" PC FIX is a troubleshooting guide created to help anyone easily solve various problems that occur while using a computer. "}</p>

            <p>{" When you try to search for a computer problem, you often come across technical terms or complicated explanations. PC FIX is structured to find problems based on the symptoms users actually experience. "}</p>

            <p>{" Where possible, solutions are organized starting with the easiest and least expensive method and progressing to more advanced steps. "}</p>

            <p>{" Because every computer environment may be different, the methods provided do not guarantee the same results in all situations. If you have important data, we recommend backing it up first and getting a professional inspection if you suspect a physical failure. "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
