import { translate } from "@/data/locales/ja";
// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import FaqItem from "@/components/FaqItem";
import SiteFooter from "@/components/locales/ja/SiteFooter";
import SiteHeader from "@/components/locales/ja/SiteHeader";
import ErrorCard from "@/components/locales/ja/ErrorCard";
import { errorCodes } from "@/data/locales/ja";
import { languageAlternates } from "@/lib/localization";
import { findProblemBySlug, problems, type Problem, } from "@/data/locales/ja";
type PageProps = {
    params: Promise<{
        slug: string;
    }>;
};
export function generateStaticParams() {
    return problems.map((problem) => ({
        slug: problem.slug,
    }));
}
export async function generateMetadata({ params, }: PageProps): Promise<Metadata> {
    const { slug } = await params;
    const problem = findProblemBySlug(slug);
    if (!problem) {
        return {
            title: "\u554F\u984C\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002 PC FIX",
            robots: {
                index: false,
                follow: false,
            },
        };
    }
    return {
        title: problem.seoTitle,
        alternates: languageAlternates(`/ja/problems/${problem.slug}`),
        description: problem.seoDescription,
        robots: {
            index: true,
            follow: true,
        },
        openGraph: {
            title: problem.seoTitle,
            description: problem.seoDescription,
            type: "article",
            siteName: "PC FIX",
        },
    };
}
export default async function ProblemPage({ params, }: PageProps) {
    const { slug } = await params;
    const problem = findProblemBySlug(slug);
    if (!problem) {
        notFound();
    }
    const relatedProblems = problem.relatedSlugs
        .map(findProblemBySlug)
        .filter((item): item is Problem => Boolean(item));
    const faq = problem.faqs;
    const baseUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://pcfixbase.com").replace(/\/$/, "");
    const relatedErrors = errorCodes.filter(entry => entry.relatedProblemSlugs.includes(problem.slug)).slice(0, 6);
    const breadcrumbJsonLd = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: [
            {
                "@type": "ListItem",
                position: 1,
                name: "PC FIX",
                item: `${baseUrl}/ja`,
            },
            {
                "@type": "ListItem",
                position: 2,
                name: problem.category,
                item: `${baseUrl}/ja/category/${encodeURIComponent(problem.category)}`,
            },
            {
                "@type": "ListItem",
                position: 3,
                name: problem.title,
            },
        ],
    };
    const articleJsonLd = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        headline: problem.title,
        url: `${baseUrl}/ja/problems/${problem.slug}`,
        inLanguage: "ja",
        description: problem.seoDescription,
        about: problem.category,
        author: {
            "@type": "Organization",
            name: "PC FIX",
        },
        publisher: {
            "@type": "Organization",
            name: "PC FIX",
        },
    };
    const faqJsonLd = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faq.map((item) => ({
            "@type": "Question",
            name: item.question,
            acceptedAnswer: {
                "@type": "Answer",
                text: item.answer,
            },
        })),
    };
    return (<main className="min-h-screen bg-slate-50 text-slate-900">
      {/* JSON-LD */}

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(breadcrumbJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(articleJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <SiteHeader />

      <div className="mx-auto max-w-5xl px-5 py-8 sm:py-12">
        {/* Breadcrumb */}

        <nav className="mb-6 flex flex-wrap items-center gap-2 text-sm text-slate-500">
          <Link href="/ja" className="transition hover:text-blue-600">
            PC FIX
          </Link>

          <span>›</span>

          <Link href={`/ja/category/${encodeURIComponent(problem.category)}`} className="transition hover:text-blue-600">
            {problem.category}
          </Link>

          <span>›</span>

          <span className="text-slate-700">
            {problem.title}
          </span>
        </nav>

        {/* 문제 소개 */}

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
          <div className="mb-4">
            <span className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">
              {problem.category}
            </span>
          </div>

          <h1 className="text-3xl font-black leading-tight tracking-tight text-slate-950 sm:text-4xl">
            {problem.title}
          </h1>

          <p className="mt-4 max-w-3xl text-base leading-7 text-slate-600 sm:text-lg">
            {problem.description}
          </p>

          <div className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-4">
            <p className="text-sm leading-6 text-blue-900">
              <strong>{" \u89E3\u6C7A\u9806\u5E8F "}</strong>

              <br />{" \u6700\u3082\u7C21\u5358\u3067\u8CBB\u7528\u306E\u304B\u304B\u308B\u65B9\u6CD5\u304B\u3089\u307E\u3068\u3081\u3089\u308C\u3066\u3044\u307E\u3059\u3002\u4E0A\u306E\u56DE\u907F\u7B56\u304B\u30891\u3064\u305A\u3064\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002 "}</p>
          </div>
        </section>

        {/* 증상 + 원인 */}

        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-black text-slate-950">{" \u3053\u306E\u3088\u3046\u306A\u75C7\u72B6\u306F\u3042\u308A\u307E\u3059\u304B\uFF1F "}</h2>

            <ul className="mt-5 space-y-3">
              {problem.symptoms.map((symptom, index) => (<li key={index} className="flex gap-3 text-sm leading-6 text-slate-700">
                    <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-blue-500"/>

                    <span>
                      {symptom}
                    </span>
                  </li>))}
            </ul>
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-black text-slate-950">{" \u4E3B\u306A\u539F\u56E0 "}</h2>

            <ul className="mt-5 space-y-3">
              {problem.causes.map((cause, index) => (<li key={index} className="flex gap-3 text-sm leading-6 text-slate-700">
                    <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-orange-500"/>

                    <span>
                      {cause}
                    </span>
                  </li>))}
            </ul>
          </section>
        </div>

        {/* 해결 방법 */}

        <section className="mt-10">
          <div>
            <h2 className="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{" \u89E3\u6C7A\u7B56 "}</h2>

            <p className="mt-2 text-sm text-slate-500">{" \u4E0A\u304B\u3089\u9806\u756A\u306B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002\u554F\u984C\u304C\u89E3\u6C7A\u3057\u305F\u3089\u3001\u6B21\u306E\u30B9\u30C6\u30C3\u30D7\u306B\u9032\u3080\u5FC5\u8981\u306F\u3042\u308A\u307E\u305B\u3093\u3002 "}</p>
          </div>

          <div className="mt-6 space-y-6">
            {problem.solutions.map((solution) => (<article key={solution.order} id={`solution-${solution.order}`} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                  <div className="border-b border-slate-100 bg-slate-50 px-5 py-5 sm:px-6">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                      <div className="flex gap-4">
                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-black text-white">
                          {solution.order}
                        </div>

                        <div>
                          <h3 className="text-lg font-bold text-slate-950 sm:text-xl">
                            {solution.title}
                          </h3>

                          <p className="mt-2 text-sm leading-6 text-slate-600">
                            {solution.reason}
                          </p>
                        </div>
                      </div>

                      <div className="flex shrink-0 flex-wrap gap-2 text-xs font-semibold">
                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u96E3\u6613\u5EA6"}{" "}
                          {translate(solution.difficulty)}
                        </span>

                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u6642\u9593"}{" "}
                          {solution.time}
                        </span>

                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u30B3\u30B9\u30C8"}{" "}
                          {solution.cost}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="px-5 py-6 sm:px-6">
                    <ol className="space-y-4">
                      {solution.steps.map((step, index) => (<li key={index} className="flex gap-3 text-sm leading-7 text-slate-700">
                            <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-slate-100 text-xs font-bold text-slate-600">
                              {index + 1}
                            </span>

                            <span>
                              {step}
                            </span>
                          </li>))}
                    </ol>

                    {solution.checkPoint && (<div className="mt-6 rounded-xl border border-green-200 bg-green-50 p-4">
                        <p className="text-sm font-bold text-green-800">{" \u78BA\u8A8D\u30DD\u30A4\u30F3\u30C8 "}</p>

                        <p className="mt-1 text-sm leading-6 text-green-700">
                          {solution.checkPoint}
                        </p>
                      </div>)}
                  </div>
                </article>))}
          </div>
        </section>

        {/* 주의사항 */}

        {problem.warning && (<section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6">
            <h2 className="text-lg font-black text-amber-900">{" \u6CE8\u610F\u4E8B\u9805 "}</h2>

            <p className="mt-2 text-sm leading-7 text-amber-800">
              {problem.warning}
            </p>
          </section>)}

        {/* 자주 묻는 질문 */}

        <section className="mt-16">
          <div>
            <h2 className="text-2xl font-black text-slate-950">{" \u3088\u304F\u3042\u308B\u8CEA\u554F "}</h2>

            <p className="mt-2 text-sm text-slate-500">{" \u3053\u306E\u554F\u984C\u306B\u95A2\u3057\u3066\u983B\u7E41\u306B\u78BA\u8A8D\u3059\u308B\u5185\u5BB9\u3092\u307E\u3068\u3081\u307E\u3057\u305F\u3002 "}</p>
          </div>

          <div className="mt-6 space-y-4">
            {faq.map((item, index) => (<FaqItem key={index} question={item.question} answer={item.answer}/>))}
          </div>
        </section>


    {/* 관련 문제 */}

        {relatedProblems.length > 0 && (<>
    {/* FAQ와 관련 문제 사이 강제 여백 */}
    <div aria-hidden="true" style={{
                height: "96px",
            }}/>

    <section style={{
                borderTop: "1px solid #e2e8f0",
                paddingTop: "48px",
            }}>
      <div>
        <h2 className="text-2xl font-black text-slate-950">{" \u95A2\u9023\u554F\u984C "}</h2>

        <p className="mt-2 text-sm text-slate-500">{" \u75C7\u72B6\u304C\u6B63\u78BA\u306B\u4E00\u81F4\u3057\u306A\u3044\u5834\u5408\u306F\u3001\u4EE5\u4E0B\u306E\u554F\u984C\u3082\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002 "}</p>
      </div>

      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        {relatedProblems.map((relatedProblem) => (<Link key={relatedProblem.slug} href={`/ja/problems/${relatedProblem.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
            <span className="text-xs font-bold text-blue-600">
              {relatedProblem.category}
            </span>

            <h3 className="mt-2 font-bold text-slate-950 group-hover:text-blue-600">
              {relatedProblem.title}
            </h3>

            <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">
              {relatedProblem.description}
            </p>

            <div className="mt-4 text-sm font-bold text-blue-600">{" \u5BFE\u51E6\u65B9\u6CD5\u3092\u898B\u308B \u2192 "}</div>
          </Link>))}
      </div>
    </section>
  </>)}
        {relatedErrors.length > 0 && (<section className="mt-12">
            <h2 className="text-2xl font-black">{"\u95A2\u9023\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9"}</h2>
            <p className="mt-2 text-sm text-slate-500">{"\u753B\u9762\u306B\u4EE5\u4E0B\u306E\u30B3\u30FC\u30C9\u304C\u8868\u793A\u3055\u308C\u3066\u3044\u308B\u5834\u5408\u306F\u3001\u30A8\u30E9\u30FC\u5225\u306E\u78BA\u8A8D\u624B\u9806\u3092\u53C2\u7167\u3057\u3066\u304F\u3060\u3055\u3044\u3002"}</p>
            <div className="mt-6 grid gap-4 sm:grid-cols-2">{relatedErrors.map(entry => <ErrorCard key={entry.slug} entry={entry}/>)}</div>
            <Link href="/ja/errors" className="mt-4 inline-block font-semibold text-blue-600">{"\u5B8C\u5168\u306A\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u3092\u898B\u308B\u2192"}</Link>
          </section>)}
        {/* 하단 CTA */}

        <section className="mt-14 rounded-3xl bg-slate-900 p-7 text-white sm:p-9">
          <h2 className="text-2xl font-black">{" \u4ED6\u306E\u75C7\u72B6\u3082\u898B\u3064\u3051\u3066\u304F\u3060\u3055\u3044 "}</h2>

          <p className="mt-3 text-sm leading-6 text-slate-300">{" PC FIX\u691C\u7D22\u30DC\u30C3\u30AF\u30B9\u306B\u73FE\u5728\u8868\u793A\u3055\u308C\u3066\u3044\u308B\u75C7\u72B6\u3092\u305D\u306E\u307E\u307E\u5165\u529B\u3059\u308B\u3068\u3001\u95A2\u9023\u3059\u308B\u554F\u984C\u304C\u898B\u3064\u304B\u308A\u307E\u3059\u3002 "}</p>

          <Link href="/ja" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900 transition hover:bg-slate-100">{" \u4ED6\u306E\u554F\u984C\u3092\u691C\u7D22\u3059\u308B\u2192 "}</Link>
        </section>
      </div>

      <SiteFooter />
    </main>);
}
