// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteFooter from "@/components/locales/ja/SiteFooter";
import SiteHeader from "@/components/locales/ja/SiteHeader";
import { problems } from "@/data/locales/ja";
import { languageAlternates } from "@/lib/localization";
type PageProps = {
    params: Promise<{
        category: string;
    }>;
};
export function generateStaticParams() {
    const categories = Array.from(new Set(problems.map((problem) => problem.category)));
    return categories.map((category) => ({
        category,
    }));
}
export async function generateMetadata({ params, }: PageProps): Promise<Metadata> {
    const { category } = await params;
    const decodedCategory = decodeURIComponent(category);
    return {
        title: `${decodedCategory} \u30C8\u30E9\u30D6\u30EB\u30B7\u30E5\u30FC\u30C6\u30A3\u30F3\u30B0PC FIX`,
        alternates: languageAlternates(`/ja/category/${encodeURIComponent(decodedCategory)}`),
        description: `${decodedCategory}\u95A2\u9023\u3059\u308B\u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u306E\u554F\u984C\u306E\u539F\u56E0\u3068\u89E3\u6C7A\u7B56\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002`,
    };
}
export default async function CategoryPage({ params }: PageProps) {
    const { category } = await params;
    const decodedCategory = decodeURIComponent(category);
    const categoryProblems = problems.filter((problem) => problem.category === decodedCategory);
    if (categoryProblems.length === 0) {
        notFound();
    }
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <div className="mx-auto max-w-6xl px-5 py-10">
        <nav className="mb-6 text-sm text-slate-500">
          <Link href="/ja" className="hover:text-blue-600">
            PC FIX
          </Link>
          <span className="mx-2">›</span>
          <span>{decodedCategory}</span>
        </nav>

        <section className="rounded-2xl border border-slate-200 bg-white p-7">
          <span className="text-sm font-bold text-blue-600">{" \u554F\u984C\u30AB\u30C6\u30B4\u30EA "}</span>

          <h1 className="mt-2 text-3xl font-black text-slate-950">
            {decodedCategory}
          </h1>

          <p className="mt-3 text-slate-500">
            {decodedCategory}{"\u306B\u95A2\u9023\u3059\u308B\u554F\u984C\u3068\u89E3\u6C7A\u7B56\u3092\u96C6\u3081\u307E\u3057\u305F\u3002 "}</p>
        </section>

        <section className="mt-8">
          <div className="mb-5 flex items-center justify-between">
            <h2 className="text-xl font-black text-slate-950">{" \u554F\u984C\u30EA\u30B9\u30C8 "}</h2>

            <span className="text-sm text-slate-400">
              {categoryProblems.length}{"\u4EF6 "}</span>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            {categoryProblems.map((problem) => (<Link key={problem.slug} href={`/ja/problems/${problem.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
                <h3 className="text-lg font-bold text-slate-950 group-hover:text-blue-600">
                  {problem.title}
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-500">
                  {problem.description}
                </p>

                <div className="mt-5 text-sm font-bold text-blue-600">{" \u5BFE\u51E6\u65B9\u6CD5\u3092\u898B\u308B \u2192 "}</div>
              </Link>))}
          </div>
        </section>
      </div>

      <SiteFooter />
    </main>);
}
