// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/en/privacy") };
import SiteFooter from "@/components/locales/en/SiteFooter";
import SiteHeader from "@/components/locales/en/SiteHeader";
export default function PrivacyPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" Privacy Policy "}</h1>

          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-600">
            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 1. Personal information processing "}</h2>

              <p className="mt-2">{" PC FIX does not currently provide a membership registration function and does not directly collect personal information such as user name or phone number. "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 2. Cookies and external services "}</h2>

              <p className="mt-2">{" Cookies or external services may be used to improve future services, analyze visit statistics, and serve advertisements. "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 3. Advertising "}</h2>

              <p className="mt-2">{" PC FIX may in the future use external advertising services, such as Google AdSense, and these services may use cookies for ad serving and measurement. "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 4. Policy change "}</h2>

              <p className="mt-2">{" The contents of this privacy policy may change as service functions change. "}</p>
            </section>

            <p className="border-t border-slate-100 pt-6 text-xs text-slate-400">{" Effective date: October 6, 2026 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
