// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/zh-CN/privacy") };
import SiteFooter from "@/components/locales/zh-CN/SiteFooter";
import SiteHeader from "@/components/locales/zh-CN/SiteHeader";
export default function PrivacyPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u9690\u79C1\u653F\u7B56 "}</h1>

          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-600">
            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 1. \u4E2A\u4EBA\u4FE1\u606F\u5904\u7406 "}</h2>

              <p className="mt-2">{" PC FIX\u76EE\u524D\u4E0D\u63D0\u4F9B\u4F1A\u5458\u6CE8\u518C\u529F\u80FD\uFF0C\u4E5F\u4E0D\u76F4\u63A5\u6536\u96C6\u7528\u6237\u540D\u6216\u7535\u8BDD\u53F7\u7801\u7B49\u4E2A\u4EBA\u4FE1\u606F\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 2. Cookie \u548C\u5916\u90E8\u670D\u52A1 "}</h2>

              <p className="mt-2">{" Cookie \u6216\u5916\u90E8\u670D\u52A1\u53EF\u7528\u4E8E\u6539\u8FDB\u672A\u6765\u7684\u670D\u52A1\u3001\u5206\u6790\u8BBF\u95EE\u7EDF\u8BA1\u6570\u636E\u4EE5\u53CA\u6295\u653E\u5E7F\u544A\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 3. \u5E7F\u544A "}</h2>

              <p className="mt-2">{" PC FIX \u5C06\u6765\u53EF\u80FD\u4F1A\u4F7F\u7528\u5916\u90E8\u5E7F\u544A\u670D\u52A1\uFF0C\u4F8B\u5982 Google AdSense\uFF0C\u5E76\u4E14\u8FD9\u4E9B\u670D\u52A1\u53EF\u80FD\u4F1A\u4F7F\u7528 cookie \u8FDB\u884C\u5E7F\u544A\u670D\u52A1\u548C\u8861\u91CF\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 4.\u653F\u7B56\u53D8\u5316 "}</h2>

              <p className="mt-2">{" \u672C\u9690\u79C1\u653F\u7B56\u7684\u5185\u5BB9\u53EF\u80FD\u4F1A\u968F\u7740\u670D\u52A1\u529F\u80FD\u7684\u53D8\u5316\u800C\u53D8\u5316\u3002 "}</p>
            </section>

            <p className="border-t border-slate-100 pt-6 text-xs text-slate-400">{" \u751F\u6548\u65E5\u671F\uFF1A2026 \u5E74 10 \u6708 6 \u65E5 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
