// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "../globals.css";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    metadataBase: new URL("https://pcfixbase.com"),
    title: "\u7535\u8111\u6545\u969C\u73B0\u8C61\u4E0E\u9519\u8BEF\u4EE3\u7801\uFF1A\u539F\u56E0\u53CA\u89E3\u51B3\u65B9\u6CD5 | PC FIX",
    description: "\u641C\u7D22\u7535\u8111\u6545\u969C\u75C7\u72B6\u548CWindows\u9519\u8BEF\u4EE3\u7801\uFF0C\u67E5\u770B\u539F\u56E0\u53CA\u5206\u6B65\u89E3\u51B3\u65B9\u6CD5\u3002",
    openGraph: {
        title: "\u7535\u8111\u6545\u969C\u73B0\u8C61\u4E0E\u9519\u8BEF\u4EE3\u7801\uFF1A\u539F\u56E0\u53CA\u89E3\u51B3\u65B9\u6CD5 | PC FIX",
        description: "\u641C\u7D22\u7535\u8111\u6545\u969C\u75C7\u72B6\u548CWindows\u9519\u8BEF\u4EE3\u7801\uFF0C\u67E5\u770B\u539F\u56E0\u53CA\u5206\u6B65\u89E3\u51B3\u65B9\u6CD5\u3002",
        siteName: "PC FIX",
        type: "website",
    },
    applicationName: "PC FIX",
    verification: {
        other: {
            "naver-site-verification": "6b525e41113b389484e65e8a18615d341056f46e",
        },
    },
    alternates: languageAlternates("/zh-CN"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
        },
    },
};
export default function RootLayout({ children, }: Readonly<{
    children: ReactNode;
}>) {
    return (<html lang="zh-CN">
      <body className="antialiased">{children}</body>
    </html>);
}
