// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function NotFound() {
    return (<main className="flex min-h-screen items-center justify-center bg-slate-50 px-5">
      <div className="text-center">
        <div className="text-7xl font-black text-slate-200">
          404
        </div>

        <h1 className="mt-5 text-3xl font-black text-slate-950">{" \u627E\u4E0D\u5230\u9875\u9762 "}</h1>

        <p className="mt-3 text-slate-500">{" \u5730\u5740\u5DF2\u66F4\u6539\u6216\u9875\u9762\u4E0D\u5B58\u5728\u3002 "}</p>

        <Link href="/zh-CN" className="mt-7 inline-flex rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white hover:bg-blue-700">{" \u524D\u5F80 PC FIX \u4E3B\u9875 "}</Link>
      </div>
    </main>);
}
