// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function SiteFooter() {
    return (<footer className="mt-16 border-t border-slate-200 bg-white">
      <div className="mx-auto max-w-6xl px-5 py-10">
        <div className="grid gap-8 sm:grid-cols-2">
          <div>
            <div className="font-black text-slate-950">PC FIX</div>

            <p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{" \u6211\u4EEC\u6574\u7406\u4E86\u8BA1\u7B97\u673A\u4E0A\u51FA\u73B0\u7684\u5404\u79CD\u95EE\u9898\u7684\u539F\u56E0\u548C\u89E3\u51B3\u65B9\u6848\uFF0C\u4EE5\u4FBF\u4EFB\u4F55\u4EBA\u90FD\u53EF\u4EE5\u8F7B\u677E\u68C0\u67E5\u3002 "}</p>
          </div>

          <div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-slate-500 sm:justify-end">
            <Link href="/zh-CN/about" className="hover:text-slate-950">{" \u670D\u52A1\u4ECB\u7ECD "}</Link>

            <Link href="/zh-CN/contact" className="hover:text-slate-950">{" \u8054\u7CFB\u6211\u4EEC "}</Link>

            <Link href="/zh-CN/privacy" className="hover:text-slate-950">{" \u9690\u79C1\u653F\u7B56 "}</Link>

            <Link href="/zh-CN/terms" className="hover:text-slate-950">{" \u4F7F\u7528\u6761\u6B3E "}</Link>
          </div>
        </div>

        <div className="mt-8 border-t border-slate-100 pt-6 text-xs leading-5 text-slate-400">
          <p>{" PC FIX \u4E2D\u7684\u4FE1\u606F\u65E8\u5728\u4F5C\u4E3A\u4E00\u822C\u6545\u969C\u6392\u9664\u7684\u53C2\u8003\u3002\u5982\u679C\u60A8\u6000\u7591\u8BBE\u5907\u5305\u542B\u91CD\u8981\u6570\u636E\u6216\u5B58\u5728\u7535\u6C14\u6216\u7269\u7406\u6545\u969C\uFF0C\u6211\u4EEC\u5EFA\u8BAE\u7531\u4E13\u4E1A\u4EBA\u5458\u8FDB\u884C\u68C0\u67E5\u3002 "}</p>

          <p className="mt-3">
            © {new Date().getFullYear()} PC FIX
          </p>
        </div>
      </div>
    </footer>);
}
