// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
import type { ErrorCodeEntry } from "@/data/locales/ja";
export default function ErrorCard({ entry }: {
    entry: ErrorCodeEntry;
}) {
    return <Link href={`/ja/errors/${entry.slug}`} className="block rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-blue-300 hover:shadow-md">
    <span className="text-xs font-bold text-blue-600">{"\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9 \u00B7 "}{entry.category}</span>
    <h3 className="mt-3 break-words text-lg font-bold text-slate-950">{entry.title}</h3>
    <p className="mt-2 text-sm leading-6 text-slate-600">{entry.description}</p>
    <p className="mt-5 text-sm font-semibold text-blue-600">{"\u5BFE\u51E6\u65B9\u6CD5\u3092\u898B\u308B \u2192"}</p>
  </Link>;
}
