// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
"use client";
import { useEffect, useState } from "react";
import { errorCodes, errorCategories } from "@/data/locales/ja";
import ErrorCard from "@/components/locales/ja/ErrorCard";
export default function ErrorBrowser() {
    const [category, setCategory] = useState("");
    useEffect(() => {
        const sync = () => {
            const params = new URLSearchParams(window.location.search);
            const legacyQuery = params.get("q")?.trim();
            if (legacyQuery) {
                window.location.replace(`/ja/?q=${encodeURIComponent(legacyQuery)}`);
                return;
            }
            const selected = params.get("category") ?? "";
            setCategory(errorCategories.includes(selected) ? selected : "");
        };
        sync();
        window.addEventListener("popstate", sync);
        return () => window.removeEventListener("popstate", sync);
    }, []);
    function update(nextCategory: string) {
        setCategory(nextCategory);
        const url = new URL(window.location.href);
        url.searchParams.delete("q");
        if (nextCategory)
            url.searchParams.set("category", nextCategory);
        else
            url.searchParams.delete("category");
        window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
    }
    const results = errorCodes.filter(entry => !category || entry.category === category);
    return <section className="mt-8">
    <div className="max-w-sm"><label htmlFor="error-category" className="mb-2 block text-sm font-semibold">{"\u30AB\u30C6\u30B4\u30EA\u30FC"}</label>
      <select id="error-category" value={category} onChange={event => update(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white p-4"><option value="">{"\u5168\u30AB\u30C6\u30B4\u30EA"}</option>{errorCategories.map(value => <option key={value}>{value}</option>)}</select>
    </div>
    <p role="status" className="my-6 text-sm text-slate-500">{results.length}{"\u72AC\u306E\u30A8\u30E9\u30FC"}</p>
    {results.length ? <div className="grid gap-4 md:grid-cols-2">{results.map(entry => <ErrorCard key={entry.slug} entry={entry}/>)}</div>
            : <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center"><p>{"\u4E00\u81F4\u3059\u308B\u30A8\u30E9\u30FC\u306F\u3042\u308A\u307E\u305B\u3093\u3002\u5225\u306E\u30AB\u30C6\u30B4\u30EA\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044\u3002"}</p><button onClick={() => update("")} className="mt-4 font-bold text-blue-600">{"\u5B8C\u5168\u306A\u30A8\u30E9\u30FC\u3092\u898B\u308B"}</button></div>}
  </section>;
}
