// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function SiteFooter() {
    return (<footer className="mt-16 border-t border-slate-200 bg-white">
      <div className="mx-auto max-w-6xl px-5 py-10">
        <div className="grid gap-8 sm:grid-cols-2">
          <div>
            <div className="font-black text-slate-950">PC FIX</div>

            <p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{" \u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u3067\u767A\u751F\u3059\u308B\u3055\u307E\u3056\u307E\u306A\u554F\u984C\u306E\u539F\u56E0\u3068\u89E3\u6C7A\u7B56\u3092\u8AB0\u3067\u3082\u7C21\u5358\u306B\u78BA\u8A8D\u3067\u304D\u308B\u3088\u3046\u306B\u6574\u7406\u3057\u307E\u3059\u3002 "}</p>
          </div>

          <div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-slate-500 sm:justify-end">
            <Link href="/ja/about" className="hover:text-slate-950">{" \u30B5\u30FC\u30D3\u30B9\u7D39\u4ECB "}</Link>

            <Link href="/ja/contact" className="hover:text-slate-950">{" \u304A\u554F\u3044\u5408\u308F\u305B "}</Link>

            <Link href="/ja/privacy" className="hover:text-slate-950">{" \u500B\u4EBA\u60C5\u5831\u51E6\u7406\u65B9\u91DD "}</Link>

            <Link href="/ja/terms" className="hover:text-slate-950">{" \u5229\u7528\u898F\u7D04 "}</Link>
          </div>
        </div>

        <div className="mt-8 border-t border-slate-100 pt-6 text-xs leading-5 text-slate-400">
          <p>{" PC FIX\u306E\u60C5\u5831\u306F\u3001\u4E00\u822C\u7684\u306A\u30C8\u30E9\u30D6\u30EB\u30B7\u30E5\u30FC\u30C6\u30A3\u30F3\u30B0\u306E\u305F\u3081\u306E\u53C2\u8003\u8CC7\u6599\u3067\u3059\u3002\u91CD\u8981\u306A\u30C7\u30FC\u30BF\u304C\u4FDD\u5B58\u3055\u308C\u305F\u6A5F\u5668\u3084\u96FB\u6C17\u7684\u30FB\u7269\u7406\u7684\u6545\u969C\u304C\u7591\u308F\u308C\u308B\u5834\u5408\u306F\u3001\u5C02\u9580\u5BB6\u306E\u70B9\u691C\u3092\u304A\u52E7\u3081\u3057\u307E\u3059\u3002 "}</p>

          <p className="mt-3">
            © {new Date().getFullYear()} PC FIX
          </p>
        </div>
      </div>
    </footer>);
}
