// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
import LanguageSelector from "@/components/LanguageSelector";
export default function SiteHeader() {
    return (<header className="border-b border-slate-200 bg-white">
      <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-4">
        <Link href="/ja" className="flex items-center gap-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-600 font-black text-white">
            P
          </div>

          <div>
            <div className="text-lg font-black tracking-tight text-slate-950">
              PC FIX
            </div>

            <div className="hidden text-[11px] text-slate-400 sm:block">{" \u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u306E\u30C8\u30E9\u30D6\u30EB\u30B7\u30E5\u30FC\u30C6\u30A3\u30F3\u30B0\u30AC\u30A4\u30C9 "}</div>
          </div>
        </Link>

        <nav className="flex items-center gap-1 text-sm font-medium text-slate-600">
          <Link href="/ja" className="rounded-lg px-3 py-2 transition hover:bg-slate-100 hover:text-slate-950">{" \u691C\u7D22 "}</Link>

          <Link href="/ja/about" className="hidden rounded-lg px-3 py-2 transition hover:bg-slate-100 hover:text-slate-950 sm:block">{" PC FIX\u306B\u3064\u3044\u3066 "}</Link>
          <LanguageSelector />
        </nav>
      </div>
    </header>);
}
