// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/zh-CN/terms") };
import SiteFooter from "@/components/locales/zh-CN/SiteFooter";
import SiteHeader from "@/components/locales/zh-CN/SiteHeader";
export default function TermsPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u4F7F\u7528\u6761\u6B3E "}</h1>

          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-600">
            <section>
              <h2 className="text-lg font-bold text-slate-950">{" \u4E00\u3001\u670D\u52A1\u5B97\u65E8 "}</h2>

              <p className="mt-2">{" PC FIX \u65E8\u5728\u63D0\u4F9B\u4E00\u822C\u4FE1\u606F\u6765\u5E2E\u52A9\u60A8\u89E3\u51B3\u8BA1\u7B97\u673A\u548C\u76F8\u5173\u8BBE\u5907\u7684\u95EE\u9898\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 2. \u4FE1\u606F\u7684\u4F7F\u7528 "}</h2>

              <p className="mt-2">{" \u7F51\u7AD9\u4E0A\u63D0\u4F9B\u7684\u4FE1\u606F\u4EC5\u4F9B\u53C2\u8003\uFF0C\u7ED3\u679C\u53EF\u80FD\u4F1A\u56E0\u7528\u6237\u7684\u8BA1\u7B97\u673A\u73AF\u5883\u800C\u5F02\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 3. \u4FDD\u62A4\u60A8\u7684\u6570\u636E\u548C\u8BBE\u5907 "}</h2>

              <p className="mt-2">{" \u6211\u4EEC\u5EFA\u8BAE\u5728\u66F4\u6539\u7CFB\u7EDF\u8BBE\u7F6E\u3001\u4F7F\u7528\u5B58\u50A8\u8BBE\u5907\u6216\u5220\u9664\u7EC4\u4EF6\u4E4B\u524D\u5907\u4EFD\u91CD\u8981\u6570\u636E\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 4\u3001\u4E13\u4E1A\u68C0\u9A8C "}</h2>

              <p className="mt-2">{" \u6211\u4EEC\u5EFA\u8BAE\u4EFB\u4F55\u53EF\u80FD\u4E0E\u5B89\u5168\u76F8\u5173\u7684\u95EE\u9898\uFF08\u4F8B\u5982\u7535\u6E90\u3001\u7535\u6C60\u6216\u635F\u574F\u7684\u90E8\u4EF6\uFF09\u7531\u4E13\u4E1A\u4EBA\u5458\u68C0\u67E5\uFF0C\u800C\u4E0D\u662F\u60A8\u81EA\u5DF1\u8FDB\u884C\u5DE5\u4F5C\u3002 "}</p>
            </section>

            <p className="border-t border-slate-100 pt-6 text-xs text-slate-400">{" \u751F\u6548\u65E5\u671F\uFF1A2026 \u5E74 10 \u6708 6 \u65E5 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
