// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/ja/terms") };
import SiteFooter from "@/components/locales/ja/SiteFooter";
import SiteHeader from "@/components/locales/ja/SiteHeader";
export default function TermsPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u5229\u7528\u898F\u7D04 "}</h1>

          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-600">
            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 1.\u30B5\u30FC\u30D3\u30B9\u76EE\u7684 "}</h2>

              <p className="mt-2">{" PC FIX\u306F\u3001\u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u304A\u3088\u3073\u95A2\u9023\u30C7\u30D0\u30A4\u30B9\u306E\u30C8\u30E9\u30D6\u30EB\u30B7\u30E5\u30FC\u30C6\u30A3\u30F3\u30B0\u306B\u5F79\u7ACB\u3064\u4E00\u822C\u7684\u306A\u60C5\u5831\u3092\u63D0\u4F9B\u3059\u308B\u3053\u3068\u3092\u76EE\u7684\u3068\u3057\u3066\u3044\u307E\u3059\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 2. \u60C5\u5831\u5229\u7528 "}</h2>

              <p className="mt-2">{" \u30B5\u30A4\u30C8\u304C\u63D0\u4F9B\u3059\u308B\u60C5\u5831\u306F\u53C2\u8003\u306E\u305F\u3081\u306B\u63D0\u4F9B\u3055\u308C\u3066\u304A\u308A\u3001\u30E6\u30FC\u30B6\u30FC\u306E\u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u74B0\u5883\u306B\u3088\u3063\u3066\u7D50\u679C\u304C\u7570\u306A\u308B\u5834\u5408\u304C\u3042\u308A\u307E\u3059\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 3.\u30C7\u30FC\u30BF\u3068\u6A5F\u5668\u306E\u4FDD\u8B77 "}</h2>

              <p className="mt-2">{" \u30B7\u30B9\u30C6\u30E0\u8A2D\u5B9A\u306E\u5909\u66F4\u3001\u30B9\u30C8\u30EC\u30FC\u30B8\u306E\u4F5C\u696D\u3001\u90E8\u54C1\u306E\u53D6\u308A\u5916\u3057\u306A\u3069\u306E\u4F5C\u696D\u3092\u9032\u3081\u308B\u524D\u306B\u3001\u91CD\u8981\u306A\u30C7\u30FC\u30BF\u3092\u30D0\u30C3\u30AF\u30A2\u30C3\u30D7\u3059\u308B\u3053\u3068\u3092\u304A\u52E7\u3081\u3057\u307E\u3059\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 4.\u5C02\u9580\u306E\u70B9\u691C "}</h2>

              <p className="mt-2">{" \u96FB\u6E90\u88C5\u7F6E\u3001\u30D0\u30C3\u30C6\u30EA\u30FC\u3001\u640D\u50B7\u3057\u305F\u90E8\u54C1\u306A\u3069\u306E\u5B89\u5168\u6027\u306B\u95A2\u9023\u3059\u308B\u53EF\u80FD\u6027\u304C\u3042\u308B\u554F\u984C\u306F\u3001\u76F4\u63A5\u4F5C\u696D\u3059\u308B\u306E\u3067\u306F\u306A\u304F\u3001\u5C02\u9580\u5BB6\u306E\u78BA\u8A8D\u3092\u304A\u52E7\u3081\u3057\u307E\u3059\u3002 "}</p>
            </section>

            <p className="border-t border-slate-100 pt-6 text-xs text-slate-400">{" \u5B9F\u65BD\u65E5\uFF1A2026\u5E7410\u67086\u65E5 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
