// Generated by scripts/generate-locales.mjs
import dictionary from "./en.json";
import { problems as originals } from "@/data/problems";
import { errorCodes as originalErrors, errorsUpdatedAt } from "@/data/errorCodes";
import { localizeData } from "@/lib/localizeData";
export const problems = localizeData(originals, dictionary);
export const errorCodes = localizeData(originalErrors, dictionary);
export const errorCategories = [...new Set(errorCodes.map(entry => entry.category))];
export const findProblemBySlug = (slug: string) => problems.find(entry => entry.slug === slug);
export const findErrorBySlug = (slug: string) => errorCodes.find(entry => entry.slug === slug);
export const translate = (text: string) => (dictionary as Record<string, string>)[text] ?? text;
export { errorsUpdatedAt };
export type { Problem } from "@/data/problems";
export type { ErrorCodeEntry } from "@/data/errorCodes";
