// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "../globals.css";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    metadataBase: new URL("https://pcfixbase.com"),
    title: "PC Troubleshooting by Symptom and Error Code | PC FIX",
    description: "Search PC symptoms and Windows error codes, and find causes and step-by-step solutions.",
    openGraph: {
        title: "PC Troubleshooting by Symptom and Error Code | PC FIX",
        description: "Search PC symptoms and Windows error codes, and find causes and step-by-step solutions.",
        siteName: "PC FIX",
        type: "website",
    },
    applicationName: "PC FIX",
    verification: {
        other: {
            "naver-site-verification": "6b525e41113b389484e65e8a18615d341056f46e",
            "google-adsense-account": "ca-pub-5914836791785057",
        },
    },
    alternates: languageAlternates("/en"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
        },
    },
};
export default function RootLayout({ children, }: Readonly<{
    children: ReactNode;
}>) {
    return (<html lang="en">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5914836791785057" crossOrigin="anonymous"/>
      </head>
      <body className="antialiased">{children}</body>
    </html>);
}
