// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "../globals.css";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    metadataBase: new URL("https://pcfixbase.com"),
    title: "PC Troubleshooting by Symptom and Error Code | PC FIX",
    description: "Check step-by-step the causes and solutions for each PC malfunction symptom, such as the computer not turning on, boot failure, black screen, blue screen, game crashing, and Internet/Wi-Fi problems.",
    applicationName: "PC FIX",
    verification: {
        other: {
            "naver-site-verification": "6b525e41113b389484e65e8a18615d341056f46e",
        },
    },
    alternates: languageAlternates("/en"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
        },
    },
};
export default function RootLayout({ children, }: Readonly<{
    children: ReactNode;
}>) {
    return (<html lang="en">
      <body className="antialiased">{children}</body>
    </html>);
}
