// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function NotFound() {
    return (<main className="flex min-h-screen items-center justify-center bg-slate-50 px-5">
      <div className="text-center">
        <div className="text-7xl font-black text-slate-200">
          404
        </div>

        <h1 className="mt-5 text-3xl font-black text-slate-950">{" Page not found "}</h1>

        <p className="mt-3 text-slate-500">{" The address has changed or the page does not exist. "}</p>

        <Link href="/en" className="mt-7 inline-flex rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white hover:bg-blue-700">{" To PC FIX Home "}</Link>
      </div>
    </main>);
}
