// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import SiteFooter from "@/components/locales/en/SiteFooter";
import SiteHeader from "@/components/locales/en/SiteHeader";
import { problems } from "@/data/locales/en";
import { searchPcFix } from "@/lib/locales/en/unifiedSearch";
const popularSlugs = [
    "game-black-screen-restart",
    "game-crash",
    "computer-slow",
    "computer-black-screen",
    "windows-blue-screen",
    "computer-shutdown",
    "computer-boot-failure",
    "usb-not-recognized",
];
export default function Home() {
    const [inputQuery, setInputQuery] = useState("");
    const [debouncedQuery, setDebouncedQuery] = useState("");
    const [isSearchStateReady, setIsSearchStateReady] = useState(false);
    const [expandedQuery, setExpandedQuery] = useState<string | null>(null);
    /*
     * 처음 홈 화면이 열릴 때 URL의 ?q= 검색어를 복원합니다.
     * 문제 상세 페이지에서 브라우저 뒤로가기를 눌렀을 때
     * 이전 검색어와 검색 결과가 그대로 돌아오게 하기 위한 처리입니다.
     */
    useEffect(() => {
        const syncFromUrl = () => {
            const params = new URLSearchParams(window.location.search);
            const queryFromUrl = params.get("q")?.trim() ?? "";
            setInputQuery(queryFromUrl);
            setDebouncedQuery(queryFromUrl);
            setIsSearchStateReady(true);
        };
        syncFromUrl();
        window.addEventListener("popstate", syncFromUrl);
        return () => {
            window.removeEventListener("popstate", syncFromUrl);
        };
    }, []);
    function updateSearchUrl(query: string) {
        const url = new URL(window.location.href);
        const normalizedQuery = query.trim();
        if (normalizedQuery) {
            url.searchParams.set("q", normalizedQuery);
        }
        else {
            url.searchParams.delete("q");
        }
        window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
    }
    /*
     * 250ms 디바운스
     * 사용자가 입력을 멈춘 뒤 검색을 실행하고,
     * 검색어를 URL의 ?q= 값에도 함께 저장합니다.
     */
    useEffect(() => {
        if (!isSearchStateReady) {
            return;
        }
        const timer = setTimeout(() => {
            const normalizedQuery = inputQuery.trim();
            setDebouncedQuery(normalizedQuery);
            updateSearchUrl(normalizedQuery);
        }, 250);
        return () => {
            clearTimeout(timer);
        };
    }, [inputQuery, isSearchStateReady]);
    const searchResults = useMemo(() => {
        if (!debouncedQuery) {
            return [];
        }
        return searchPcFix(debouncedQuery);
    }, [debouncedQuery]);
    const popularProblems = popularSlugs
        .map((slug) => problems.find((problem) => problem.slug === slug))
        .filter(Boolean);
    const categories = Array.from(new Set(problems.map((problem) => problem.category)));
    const isSearching = debouncedQuery.length > 0;
    function handleExampleSearch(example: string) {
        setInputQuery(example);
        setDebouncedQuery(example);
        updateSearchUrl(example);
    }
    function handleClear() {
        setInputQuery("");
        setDebouncedQuery("");
        updateSearchUrl("");
    }
    return (<main className="min-h-screen bg-slate-50 text-slate-900">
      <SiteHeader />

      {/* HERO */}
      <section className="border-b border-slate-200 bg-white">
        <div className="mx-auto max-w-5xl px-5 py-16 text-center sm:py-24">
          <div className="mx-auto mb-5 inline-flex rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700">{" Search PC symptoms and error codes "}</div>

          <h1 className="text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">{" Something wrong with your PC? "}<br />
            <span className="text-blue-600">{" Find out what to check first. "}</span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-500 sm:text-lg">{" Look for symptoms of various problems that occur on your PC, including power, boot, screen, blue screen, games, and Internet. "}<br className="hidden sm:block"/>{" Enter the symptoms you are experiencing or the error code shown on your screen. "}</p>

          {/* 검색 영역 */}
          <div className="mx-auto mt-9" style={{
            width: "min(760px, 100%)",
        }}>
            <div style={{
            position: "relative",
            width: "100%",
        }}>
              <input type="text" aria-label="Search PC symptoms or error codes" value={inputQuery} onChange={(event) => setInputQuery(event.target.value)} placeholder="Try: black screen while gaming, 0xc0000005, Code 43" style={{
            display: "block",
            width: "100%",
            height: "64px",
            boxSizing: "border-box",
            paddingLeft: "22px",
            paddingRight: "54px",
            borderRadius: "16px",
            border: "1px solid #cbd5e1",
            backgroundColor: "#ffffff",
            fontSize: "16px",
            outline: "none",
            boxShadow: "0 8px 24px rgba(15, 23, 42, 0.08)",
        }} className="placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/>

              {inputQuery && (<button type="button" onClick={handleClear} aria-label="Clear search term" style={{
                position: "absolute",
                right: "14px",
                top: "50%",
                transform: "translateY(-50%)",
                width: "34px",
                height: "34px",
                borderRadius: "8px",
            }} className="text-slate-400 transition hover:bg-slate-100 hover:text-slate-700">
                  ✕
                </button>)}
            </div>

            <p className="mt-4 text-xs text-slate-400">{" In addition to symptoms, you can search for error codes such as 0xc0000005 and Code 43. "}</p>

            {/* 빠른 검색 */}
            <div className="mt-5 flex flex-wrap justify-center gap-2 text-xs text-slate-500">
              <button type="button" onClick={() => handleExampleSearch("While playing a game, a black screen appears and reboots.")} className="rounded-full border border-slate-200 bg-white px-4 py-2 transition hover:border-blue-300 hover:text-blue-600">{" black screen while gaming "}</button>

              <button type="button" onClick={() => handleExampleSearch("The game keeps crashing")} className="rounded-full border border-slate-200 bg-white px-4 py-2 transition hover:border-blue-300 hover:text-blue-600">{" Game crashing "}</button>

              <button type="button" onClick={() => handleExampleSearch("My computer is so slow")} className="rounded-full border border-slate-200 bg-white px-4 py-2 transition hover:border-blue-300 hover:text-blue-600">{" computer slows down "}</button>

              <button type="button" onClick={() => handleExampleSearch("The internet suddenly doesn't work")} className="rounded-full border border-slate-200 bg-white px-4 py-2 transition hover:border-blue-300 hover:text-blue-600">{" No internet "}</button>
            </div>
          </div>
        </div>
      </section>

      {/* 본문 */}
      <div className="mx-auto max-w-6xl px-5 py-12">
        {isSearching ? (<section>
            <div className="mb-6 flex items-end justify-between gap-4">
              <div>
                <h2 className="text-2xl font-black text-slate-950">{" Search results "}</h2>

                <p className="mt-1 text-sm text-slate-500">
                  &quot;{debouncedQuery}{"\"Problems and errors related to: "}</p>
              </div>

              <span className="text-sm text-slate-400">
                {searchResults.length}{" results "}</span>
            </div>

            {searchResults.length > 0 ? (<>
                <div className="grid gap-4 md:grid-cols-2">
                  {searchResults
                    .slice(0, expandedQuery === debouncedQuery ? undefined : 10)
                    .map((problem, index) => (<Link key={problem.href} href={problem.href} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
                        <div className="flex items-center justify-between gap-3">
                          <span className="text-xs font-bold text-blue-600">
                            {problem.category}
                          </span>

                          {index === 0 && (<span className="rounded-full bg-green-50 px-2.5 py-1 text-[11px] font-bold text-green-700">{" Best match "}</span>)}
                        </div>

                        <h3 className="mt-3 text-lg font-bold text-slate-950 group-hover:text-blue-600">
                          {problem.title}
                        </h3>

                        <p className="mt-2 text-sm leading-6 text-slate-500">
                          {problem.description}
                        </p>

                        <div className="mt-5 text-sm font-semibold text-blue-600">{" View solutions \u2192 "}</div>
                      </Link>))}
                </div>

                {searchResults.length > 10 && expandedQuery !== debouncedQuery && (<div className="mt-6 text-center"><button type="button" onClick={() => setExpandedQuery(debouncedQuery)} className="rounded-xl border border-blue-200 bg-white px-5 py-3 text-sm font-bold text-blue-600">{"View more search results ("}{searchResults.length - 10}{" more)"}</button></div>)}
                <div className="mt-8 text-center">
                  <button type="button" onClick={handleClear} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-bold text-slate-700 transition hover:border-blue-300 hover:text-blue-600">{" Search for other issues "}</button>
                </div>
              </>) : (<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center">
                <div className="text-4xl">
                  🔎
                </div>

                <h3 className="mt-4 text-lg font-bold text-slate-950">{" I couldn't find any related issues. "}</h3>

                <p className="mt-2 text-sm leading-6 text-slate-500">{" Please enter your symptoms in more detail. "}<br />{" Example: \u201CThe screen turns off during the game, but the PC stays on.\u201D "}</p>

                <button type="button" onClick={handleClear} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-blue-700">{" Search again "}</button>
              </div>)}
          </section>) : (<>
            {/* 자주 발생하는 문제 */}
            <section>
              <div className="mb-6">
                <h2 className="text-2xl font-black text-slate-950">{" Common PC problems "}</h2>

                <p className="mt-1 text-sm text-slate-500">{" Check out the most common PC problems first. "}</p>
              </div>

              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {popularProblems.map((problem) => {
                if (!problem) {
                    return null;
                }
                return (<Link key={problem.slug} href={`/en/problems/${problem.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
                      <span className="text-xs font-bold text-blue-600">
                        {problem.category}
                      </span>

                      <h3 className="mt-2 font-bold leading-6 text-slate-950 group-hover:text-blue-600">
                        {problem.title}
                      </h3>

                      <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">
                        {problem.description}
                      </p>
                    </Link>);
            })}
              </div>
            </section>

            {/* 카테고리 */}
            <section className="mt-14">
              <div className="mb-6">
                <h2 className="text-2xl font-black text-slate-950">{" Browse by category "}</h2>

                <p className="mt-1 text-sm text-slate-500">{" If you know where the problem is, look for it in the categories. "}</p>
              </div>

              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
                {categories.map((category) => {
                const count = problems.filter((problem) => problem.category === category).length;
                return (<Link key={category} href={`/en/category/${encodeURIComponent(category)}`} className="rounded-xl border border-slate-200 bg-white p-5 transition hover:border-blue-300 hover:shadow-sm">
                      <div className="font-bold text-slate-950">
                        {category}
                      </div>

                      <div className="mt-1 text-xs text-slate-400">{" problem "}{count}{" results "}</div>
                    </Link>);
            })}
              </div>
            </section>

            {/* 사용 방법 */}
            <section className="mt-14 rounded-3xl bg-slate-900 px-6 py-10 text-white sm:px-10">
              <h2 className="text-2xl font-black">{" You can use PC FIX like this: "}</h2>

              <div className="mt-8 grid gap-6 md:grid-cols-3">
                <div>
                  <div className="text-sm font-black text-blue-400">
                    01
                  </div>

                  <h3 className="mt-2 font-bold">{" Search for symptoms as is "}</h3>

                  <p className="mt-2 text-sm leading-6 text-slate-300">{" Instead of jargon, use what you actually see. "}</p>
                </div>

                <div>
                  <div className="text-sm font-black text-blue-400">
                    02
                  </div>

                  <h3 className="mt-2 font-bold">{" Check it out the easy way "}</h3>

                  <p className="mt-2 text-sm leading-6 text-slate-300">{" We will guide you step by step, starting with solutions that are less costly and less risky. "}</p>
                </div>

                <div>
                  <div className="text-sm font-black text-blue-400">
                    03
                  </div>

                  <h3 className="mt-2 font-bold">{" Proceed only until resolved "}</h3>

                  <p className="mt-2 text-sm leading-6 text-slate-300">{" If the problem is resolved, there is no need to proceed to more difficult steps. "}</p>
                </div>
              </div>
            </section>
          </>)}
      </div>

      <SiteFooter />
    </main>);
}
