// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/locales/ja/SiteHeader";
import SiteFooter from "@/components/locales/ja/SiteFooter";
import ErrorBrowser from "@/components/locales/ja/ErrorBrowser";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    title: "PC\u30FBWindows\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u691C\u7D22\u3068\u89E3\u6C7A\u65B9\u6CD5PC FIX",
    description: "\u30D6\u30EB\u30FC\u30B9\u30AF\u30EA\u30FC\u30F3\u3001Windows Update\u3001\u30C7\u30D0\u30A4\u30B9\u30DE\u30CD\u30FC\u30B8\u30E3\u3001\u30B0\u30E9\u30D5\u30A3\u30C3\u30AF\u30B9\u3001\u30B2\u30FC\u30E0\u3001\u30D6\u30E9\u30A6\u30B6\u3001DLL\u30A8\u30E9\u30FC\u306E\u610F\u5473\u3068\u6BB5\u968E\u7684\u306A\u56DE\u907F\u7B56\u3092\u898B\u3064\u3051\u3066\u304F\u3060\u3055\u3044\u3002",
    alternates: languageAlternates("/ja/errors"),
};
export default function ErrorsPage() {
    return <main className="min-h-screen bg-slate-50 text-slate-900"><SiteHeader />
    <div className="mx-auto max-w-6xl px-5 py-12"><h1 className="text-3xl font-black sm:text-4xl">{"\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u4E00\u89A7"}</h1>
      <p className="mt-4 max-w-3xl leading-7 text-slate-600">{"\u30AB\u30C6\u30B4\u30EA\u5225\u306E\u30A8\u30E9\u30FC\u3092\u3054\u89A7\u304F\u3060\u3055\u3044\u3002\u75C7\u72B6\u3068\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u306E\u691C\u7D22\u306F\u3001\u30E1\u30A4\u30F3\u691C\u7D22\u30DC\u30C3\u30AF\u30B9\u3067\u4E00\u5EA6\u306B\u884C\u3046\u3053\u3068\u304C\u3067\u304D\u307E\u3059\u3002"}</p>
      <Link href="/ja" className="mt-5 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">{"\u7D71\u5408\u691C\u7D22\u3067\u691C\u7D22\u2192"}</Link><ErrorBrowser /></div><SiteFooter /></main>;
}
