// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteFooter from "@/components/locales/zh-CN/SiteFooter";
import SiteHeader from "@/components/locales/zh-CN/SiteHeader";
import { problems } from "@/data/locales/zh-CN";
import { languageAlternates } from "@/lib/localization";
type PageProps = {
    params: Promise<{
        category: string;
    }>;
};
export function generateStaticParams() {
    const categories = Array.from(new Set(problems.map((problem) => problem.category)));
    return categories.map((category) => ({
        category,
    }));
}
export async function generateMetadata({ params, }: PageProps): Promise<Metadata> {
    const { category } = await params;
    const decodedCategory = decodeURIComponent(category);
    return {
        title: `${decodedCategory} \u6545\u969C\u6392\u9664 |PC FIX`,
        alternates: languageAlternates(`/zh-CN/category/${encodeURIComponent(decodedCategory)}`),
        description: `${decodedCategory}\u627E\u51FA\u4E0E \u76F8\u5173\u7684\u8BA1\u7B97\u673A\u95EE\u9898\u7684\u539F\u56E0\u548C\u89E3\u51B3\u65B9\u6848\u3002`,
    };
}
export default async function CategoryPage({ params }: PageProps) {
    const { category } = await params;
    const decodedCategory = decodeURIComponent(category);
    const categoryProblems = problems.filter((problem) => problem.category === decodedCategory);
    if (categoryProblems.length === 0) {
        notFound();
    }
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <div className="mx-auto max-w-6xl px-5 py-10">
        <nav className="mb-6 text-sm text-slate-500">
          <Link href="/zh-CN" className="hover:text-blue-600">
            PC FIX
          </Link>
          <span className="mx-2">›</span>
          <span>{decodedCategory}</span>
        </nav>

        <section className="rounded-2xl border border-slate-200 bg-white p-7">
          <span className="text-sm font-bold text-blue-600">{" \u95EE\u9898\u7C7B\u522B "}</span>

          <h1 className="mt-2 text-3xl font-black text-slate-950">
            {decodedCategory}
          </h1>

          <p className="mt-3 text-slate-500">
            {decodedCategory}{"\u6211\u4EEC\u6536\u96C6\u4E86\u76F8\u5173\u95EE\u9898\u548C\u89E3\u51B3\u65B9\u6848\u3002 "}</p>
        </section>

        <section className="mt-8">
          <div className="mb-5 flex items-center justify-between">
            <h2 className="text-xl font-black text-slate-950">{" \u95EE\u9898\u6E05\u5355 "}</h2>

            <span className="text-sm text-slate-400">
              {categoryProblems.length}{"\u6761 "}</span>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            {categoryProblems.map((problem) => (<Link key={problem.slug} href={`/zh-CN/problems/${problem.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
                <h3 className="text-lg font-bold text-slate-950 group-hover:text-blue-600">
                  {problem.title}
                </h3>

                <p className="mt-2 text-sm leading-6 text-slate-500">
                  {problem.description}
                </p>

                <div className="mt-5 text-sm font-bold text-blue-600">{" \u67E5\u770B\u89E3\u51B3\u65B9\u6CD5 \u2192 "}</div>
              </Link>))}
          </div>
        </section>
      </div>

      <SiteFooter />
    </main>);
}
