// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
"use client";
import { useEffect, useState } from "react";
import { errorCodes, errorCategories } from "@/data/locales/en";
import ErrorCard from "@/components/locales/en/ErrorCard";
export default function ErrorBrowser() {
    const [category, setCategory] = useState("");
    useEffect(() => {
        const sync = () => {
            const params = new URLSearchParams(window.location.search);
            const legacyQuery = params.get("q")?.trim();
            if (legacyQuery) {
                window.location.replace(`/en/?q=${encodeURIComponent(legacyQuery)}`);
                return;
            }
            const selected = params.get("category") ?? "";
            setCategory(errorCategories.includes(selected) ? selected : "");
        };
        sync();
        window.addEventListener("popstate", sync);
        return () => window.removeEventListener("popstate", sync);
    }, []);
    function update(nextCategory: string) {
        setCategory(nextCategory);
        const url = new URL(window.location.href);
        url.searchParams.delete("q");
        if (nextCategory)
            url.searchParams.set("category", nextCategory);
        else
            url.searchParams.delete("category");
        window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
    }
    const results = errorCodes.filter(entry => !category || entry.category === category);
    return <section className="mt-8">
    <div className="max-w-sm"><label htmlFor="error-category" className="mb-2 block text-sm font-semibold">{"Category"}</label>
      <select id="error-category" value={category} onChange={event => update(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white p-4"><option value="">{"All categories"}</option>{errorCategories.map(value => <option key={value}>{value}</option>)}</select>
    </div>
    <p role="status" className="my-6 text-sm text-slate-500">{results.length}{"dog error"}</p>
    {results.length ? <div className="grid gap-4 md:grid-cols-2">{results.map(entry => <ErrorCard key={entry.slug} entry={entry}/>)}</div>
            : <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center"><p>{"There are no matching errors. Please select a different category."}</p><button onClick={() => update("")} className="mt-4 font-bold text-blue-600">{"View all errors"}</button></div>}
  </section>;
}
