// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function SiteFooter() {
    return (<footer className="mt-16 border-t border-slate-200 bg-white">
      <div className="mx-auto max-w-6xl px-5 py-10">
        <div className="grid gap-8 sm:grid-cols-2">
          <div>
            <div className="font-black text-slate-950">PC FIX</div>

            <p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{" We organize the causes and solutions to various problems that occur on computers so that anyone can easily check them. "}</p>
          </div>

          <div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-slate-500 sm:justify-end">
            <Link href="/en/about" className="hover:text-slate-950">{" Service introduction "}</Link>

            <Link href="/en/contact" className="hover:text-slate-950">{" Contact us "}</Link>

            <Link href="/en/privacy" className="hover:text-slate-950">{" Privacy Policy "}</Link>

            <Link href="/en/terms" className="hover:text-slate-950">{" Terms of Use "}</Link>
          </div>
        </div>

        <div className="mt-8 border-t border-slate-100 pt-6 text-xs leading-5 text-slate-400">
          <p>{" The information in PC FIX is intended as a reference for general troubleshooting. If you suspect a device containing important data or an electrical or physical malfunction, we recommend inspection by a professional. "}</p>

          <p className="mt-3">
            © {new Date().getFullYear()} PC FIX
          </p>
        </div>
      </div>
    </footer>);
}
