// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/ja/privacy") };
import SiteFooter from "@/components/locales/ja/SiteFooter";
import SiteHeader from "@/components/locales/ja/SiteHeader";
export default function PrivacyPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" \u500B\u4EBA\u60C5\u5831\u51E6\u7406\u65B9\u91DD "}</h1>

          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-600">
            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 1. \u500B\u4EBA\u60C5\u5831\u51E6\u7406 "}</h2>

              <p className="mt-2">{" PC FIX\u306F\u73FE\u5728\u3001\u4F1A\u54E1\u767B\u9332\u6A5F\u80FD\u3092\u63D0\u4F9B\u3057\u3066\u304A\u3089\u305A\u3001\u30E6\u30FC\u30B6\u30FC\u306E\u540D\u524D\u3001\u96FB\u8A71\u756A\u53F7\u306A\u3069\u306E\u500B\u4EBA\u60C5\u5831\u3092\u76F4\u63A5\u53CE\u96C6\u3057\u307E\u305B\u3093\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 2. \u30AF\u30C3\u30AD\u30FC\u3068\u5916\u90E8\u30B5\u30FC\u30D3\u30B9 "}</h2>

              <p className="mt-2">{" \u4ECA\u5F8C\u306E\u30B5\u30FC\u30D3\u30B9\u306E\u6539\u5584\u3001\u8A2A\u554F\u7D71\u8A08\u306E\u5206\u6790\u3001\u5E83\u544A\u306E\u63D0\u4F9B\u306B\u306F\u3001Cookie \u307E\u305F\u306F\u5916\u90E8\u30B5\u30FC\u30D3\u30B9\u3092\u4F7F\u7528\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u307E\u3059\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 3. \u5E83\u544A "}</h2>

              <p className="mt-2">{" PC FIX \u3067\u306F\u3001\u4ECA\u5F8C Google AdSense \u306A\u3069\u306E\u5916\u90E8\u5E83\u544A\u30B5\u30FC\u30D3\u30B9\u3092\u5229\u7528\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u3001\u305D\u306E\u30B5\u30FC\u30D3\u30B9\u3067\u5E83\u544A\u3092\u63D0\u4F9B\u304A\u3088\u3073\u6E2C\u5B9A\u3059\u308B\u305F\u3081\u306B Cookie \u3092\u4F7F\u7528\u3059\u308B\u3053\u3068\u304C\u3067\u304D\u307E\u3059\u3002 "}</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-950">{" 4. \u65B9\u91DD\u306E\u5909\u66F4 "}</h2>

              <p className="mt-2">{" \u30B5\u30FC\u30D3\u30B9\u6A5F\u80FD\u306E\u5909\u66F4\u306B\u3088\u308A\u3001\u672C\u30D7\u30E9\u30A4\u30D0\u30B7\u30FC\u30DD\u30EA\u30B7\u30FC\u306E\u5185\u5BB9\u304C\u5909\u66F4\u3055\u308C\u308B\u3053\u3068\u304C\u3042\u308A\u307E\u3059\u3002 "}</p>
            </section>

            <p className="border-t border-slate-100 pt-6 text-xs text-slate-400">{" \u5B9F\u65BD\u65E5\uFF1A2026\u5E7410\u67086\u65E5 "}</p>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
