// 번역 JSON을 수정한 뒤 실행: node scripts/generate-locales.mjs
// 한국어 소스를 기준으로 외국어 페이지를 재생성합니다. 생성 파일을 직접 수정하지 마세요.
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { fileURLToPath } from "node:url";
import { sourceFiles, loadData, collectStrings } from "./translate-content.mjs";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const korean = /[가-힣]/;
const selected = process.argv.find(argument => argument.startsWith("--locale="))?.split("=")[1];
const languages = ["en", "ja", "zh-CN"].filter(locale => !selected || locale === selected);
const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
const categoryFile = path.join(root, "data/categoryLocales.json");
const categories = fs.existsSync(categoryFile) ? JSON.parse(fs.readFileSync(categoryFile, "utf8")) : {};
for (const problem of loadData("data/problems.ts").problems) categories[problem.category] ??= {};
function write(filename, text) { fs.mkdirSync(path.dirname(filename), { recursive: true }); fs.writeFileSync(filename, text); }
for (const locale of languages) {
  const dictionaryPath = path.join(root, `data/locales/${locale}.json`);
  const overrides = JSON.parse(fs.readFileSync(path.join(root, "data/locales/uiOverrides.json"), "utf8"));
  const dictionary = { ...JSON.parse(fs.readFileSync(dictionaryPath, "utf8")), ...overrides[locale] };
  fs.writeFileSync(dictionaryPath, JSON.stringify(dictionary, null, 2) + "\n");
  const missing = collectStrings().filter(value => !dictionary[value]);
  if (missing.length) throw new Error(`${locale}: ${missing.length} missing strings; run translate-content.mjs first`);
  Object.keys(categories).forEach(category => { categories[category][locale] = dictionary[category]; });
  write(path.join(root, `data/locales/${locale}.ts`), `// Generated by scripts/generate-locales.mjs\nimport dictionary from "./${locale}.json";\nimport { problems as originals } from "@/data/problems";\nimport { errorCodes as originalErrors, errorsUpdatedAt } from "@/data/errorCodes";\nimport { localizeData } from "@/lib/localizeData";\nexport const problems = localizeData(originals, dictionary);\nexport const errorCodes = localizeData(originalErrors, dictionary);\nexport const errorCategories = [...new Set(errorCodes.map(entry => entry.category))];\nexport const findProblemBySlug = (slug: string) => problems.find(entry => entry.slug === slug);\nexport const findErrorBySlug = (slug: string) => errorCodes.find(entry => entry.slug === slug);\nexport const translate = (text: string) => (dictionary as Record<string, string>)[text] ?? text;\nexport { errorsUpdatedAt };\nexport type { Problem } from "@/data/problems";\nexport type { ErrorCodeEntry } from "@/data/errorCodes";\n`);
  for (const filename of sourceFiles) {
    let sourceText = fs.readFileSync(path.join(root, filename), "utf8");
    if (filename.endsWith("layout.tsx")) sourceText = sourceText.replace(/import ["']\.\/?(?:\.\/)?globals.css["'];/, 'import "../globals.css";');
    const source = ts.createSourceFile(filename, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
    let needsTranslate = false;
    function text(value) {
      if (value === "개") return locale === "en" ? " results" : locale === "ja" ? "件" : "条";
      if (value === "개)") return locale === "en" ? " more)" : locale === "ja" ? "件)" : "条)";
      if (korean.test(value)) {
        if (!dictionary[value]) throw new Error(`Missing translation ${filename}: ${value}`);
        const leading = value.match(/^\s*/)[0], trailing = value.match(/\s*$/)[0];
        return leading + dictionary[value].trim() + trailing;
      }
      if (value === "@/data/problems" || value === "@/data/errorCodes") return `@/data/locales/${locale}`;
      if (["@/components/SiteHeader", "@/components/SiteFooter", "@/components/ErrorBrowser", "@/components/ErrorCard"].includes(value)) return value.replace("@/components/", `@/components/locales/${locale}/`);
      if (["@/lib/unifiedSearch", "@/lib/errorSearch"].includes(value)) return value.replace("@/lib/", `@/lib/locales/${locale}/`);
      if (value === "ko") return locale;
      if (value === "/") return `/${locale}`;
      if (/^\/(?:problems|errors|category|about|contact|privacy|terms)(?:\/|$)/.test(value) || value.startsWith("/?")) return `/${locale}${value}`;
      return value;
    }
    const transformed = ts.transform(source, [context => {
      const visit = node => {
        if (ts.isJsxText(node) && korean.test(node.text)) {
          const key = node.text.replace(/\s+/g, " ").trim();
          const value = (/^\s/.test(node.text) ? " " : "") + text(key).replace(/&quot;/g, '"').replace(/&amp;/g, "&") + (/\s$/.test(node.text) ? " " : "");
          return ts.factory.createJsxExpression(undefined, ts.factory.createStringLiteral(value));
        }
        if (ts.isStringLiteral(node)) return ts.factory.createStringLiteral(text(node.text));
        if (ts.isNoSubstitutionTemplateLiteral(node)) return ts.factory.createNoSubstitutionTemplateLiteral(text(node.text));
        if (ts.isTemplateHead(node)) return ts.factory.createTemplateHead(text(node.text));
        if (ts.isTemplateMiddle(node)) return ts.factory.createTemplateMiddle(text(node.text));
        if (ts.isTemplateTail(node)) return ts.factory.createTemplateTail(text(node.text));
        if (ts.isPropertyAccessExpression(node) && node.name.text === "difficulty") {
          needsTranslate = true;
          return ts.factory.createCallExpression(ts.factory.createIdentifier("translate"), undefined, [node]);
        }
        return ts.visitEachChild(node, visit, context);
      };
      return node => ts.visitNode(node, visit);
    }]);
    let output = "// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.\n" + printer.printFile(transformed.transformed[0]);
    transformed.dispose();
    if (needsTranslate) output = `import { translate } from "@/data/locales/${locale}";\n` + output;
    let destination;
    if (filename.startsWith("app/")) {
      const relative = filename.replace(/^app\/(?:\(ko\)\/)?/, "");
      destination = path.join(root, `app/${locale}/${relative}`);
    } else if (filename.startsWith("components/")) destination = path.join(root, filename.replace("components/", `components/locales/${locale}/`));
    else destination = path.join(root, filename.replace("lib/", `lib/locales/${locale}/`));
    write(destination, output.replace(/[\t ]+$/gm, ""));
  }
}
write(path.join(root, "data/categoryLocales.json"), JSON.stringify(categories, null, 2) + "\n");
console.log(`Generated ${languages.join(", ")} routes, components and data modules.`);
