// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "../globals.css";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    metadataBase: new URL("https://pcfixbase.com"),
    title: "PC\u306E\u75C7\u72B6\u30FB\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u5225\u306E\u539F\u56E0\u3068\u5BFE\u51E6\u65B9\u6CD5 | PC FIX",
    description: "\u30B3\u30F3\u30D4\u30E5\u30FC\u30BF\u306E\u96FB\u6E90\u304C\u5165\u3089\u306A\u3044\u3001\u8D77\u52D5\u3067\u304D\u306A\u3044\u3001\u9ED2\u3044\u753B\u9762\u3001\u30D6\u30EB\u30FC\u30B9\u30AF\u30EA\u30FC\u30F3\u3001\u30B2\u30FC\u30E0\u306E\u30AF\u30E9\u30C3\u30B7\u30E5\u3001\u30A4\u30F3\u30BF\u30FC\u30CD\u30C3\u30C8\u30FBWi-Fi\u306E\u554F\u984C\u306A\u3069\u3001PC\u306E\u6545\u969C\u306E\u75C7\u72B6\u5225\u306E\u539F\u56E0\u3068\u89E3\u6C7A\u7B56\u3092\u6BB5\u968E\u7684\u306B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
    applicationName: "PC FIX",
    verification: {
        other: {
            "naver-site-verification": "6b525e41113b389484e65e8a18615d341056f46e",
        },
    },
    alternates: languageAlternates("/ja"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
        },
    },
};
export default function RootLayout({ children, }: Readonly<{
    children: ReactNode;
}>) {
    return (<html lang="ja">
      <body className="antialiased">{children}</body>
    </html>);
}
