// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "../globals.css";
import { languageAlternates } from "@/lib/localization";
export const metadata: Metadata = {
    metadataBase: new URL("https://pcfixbase.com"),
    title: "PC\u306E\u75C7\u72B6\u30FB\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u5225\u306E\u539F\u56E0\u3068\u5BFE\u51E6\u65B9\u6CD5 | PC FIX",
    description: "PC\u306E\u4E0D\u5177\u5408\u3084Windows\u306E\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u3092\u691C\u7D22\u3057\u3001\u539F\u56E0\u3068\u89E3\u6C7A\u624B\u9806\u3092\u78BA\u8A8D\u3067\u304D\u307E\u3059\u3002",
    openGraph: {
        title: "PC\u306E\u75C7\u72B6\u30FB\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u5225\u306E\u539F\u56E0\u3068\u5BFE\u51E6\u65B9\u6CD5 | PC FIX",
        description: "PC\u306E\u4E0D\u5177\u5408\u3084Windows\u306E\u30A8\u30E9\u30FC\u30B3\u30FC\u30C9\u3092\u691C\u7D22\u3057\u3001\u539F\u56E0\u3068\u89E3\u6C7A\u624B\u9806\u3092\u78BA\u8A8D\u3067\u304D\u307E\u3059\u3002",
        siteName: "PC FIX",
        type: "website",
    },
    applicationName: "PC FIX",
    verification: {
        other: {
            "naver-site-verification": "6b525e41113b389484e65e8a18615d341056f46e",
            "google-adsense-account": "ca-pub-5914836791785057",
        },
    },
    alternates: languageAlternates("/ja"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
        },
    },
};
export default function RootLayout({ children, }: Readonly<{
    children: ReactNode;
}>) {
    return (<html lang="ja">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5914836791785057" crossOrigin="anonymous"/>
      </head>
      <body className="antialiased">{children}</body>
    </html>);
}
