// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import Link from "next/link";
export default function NotFound() {
    return (<main className="flex min-h-screen items-center justify-center bg-slate-50 px-5">
      <div className="text-center">
        <div className="text-7xl font-black text-slate-200">
          404
        </div>

        <h1 className="mt-5 text-3xl font-black text-slate-950">{" \u30DA\u30FC\u30B8\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093 "}</h1>

        <p className="mt-3 text-slate-500">{" \u30A2\u30C9\u30EC\u30B9\u304C\u5909\u66F4\u3055\u308C\u305F\u304B\u5B58\u5728\u3057\u306A\u3044\u30DA\u30FC\u30B8\u3067\u3059\u3002 "}</p>

        <Link href="/ja" className="mt-7 inline-flex rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white hover:bg-blue-700">{" PC FIX\u30DB\u30FC\u30E0\u3078 "}</Link>
      </div>
    </main>);
}
