// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import { languageAlternates } from "@/lib/localization";
export const metadata = { alternates: languageAlternates("/en/contact") };
import SiteFooter from "@/components/locales/en/SiteFooter";
import SiteHeader from "@/components/locales/en/SiteHeader";
export default function ContactPage() {
    return (<main className="min-h-screen bg-slate-50">
      <SiteHeader />

      <article className="mx-auto max-w-3xl px-5 py-12">
        <div className="rounded-2xl border border-slate-200 bg-white p-7 sm:p-10">
          <h1 className="text-3xl font-black text-slate-950">{" Contact us "}</h1>

          <p className="mt-6 leading-7 text-slate-600">{" This is a page for PC FIX content errors, correction requests, partnerships, and other inquiries. "}</p>

          <div className="mt-8 rounded-xl bg-slate-50 p-5">
            <h2 className="font-bold text-slate-950">{" How to contact us "}</h2>

            <p className="mt-2 text-sm leading-6 text-slate-500">{" Please send any inquiries to the email address below. "}</p>

            <a href="mailto:contact@pcfixbase.com" className="mt-3 inline-block font-semibold text-blue-600 hover:underline">
              contact@pcfixbase.com
            </a>
          </div>
        </div>
      </article>

      <SiteFooter />
    </main>);
}
