import DisplayAd from "@/components/DisplayAd";
import { translate } from "@/data/locales/zh-CN";
// Generated by scripts/generate-locales.mjs; edit Korean sources or translation JSON.
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import FaqItem from "@/components/FaqItem";
import SiteFooter from "@/components/locales/zh-CN/SiteFooter";
import SiteHeader from "@/components/locales/zh-CN/SiteHeader";
import ErrorCard from "@/components/locales/zh-CN/ErrorCard";
import { errorCodes } from "@/data/locales/zh-CN";
import { languageAlternates } from "@/lib/localization";
import { findProblemBySlug, problems, type Problem, } from "@/data/locales/zh-CN";
type PageProps = {
    params: Promise<{
        slug: string;
    }>;
};
export function generateStaticParams() {
    return problems.map((problem) => ({
        slug: problem.slug,
    }));
}
export async function generateMetadata({ params, }: PageProps): Promise<Metadata> {
    const { slug } = await params;
    const problem = findProblemBySlug(slug);
    if (!problem) {
        return {
            title: "\u6CA1\u53D1\u73B0\u95EE\u9898 |PC FIX",
            robots: {
                index: false,
                follow: false,
            },
        };
    }
    return {
        title: problem.seoTitle,
        alternates: languageAlternates(`/zh-CN/problems/${problem.slug}`),
        description: problem.seoDescription,
        robots: {
            index: true,
            follow: true,
        },
        openGraph: {
            title: problem.seoTitle,
            description: problem.seoDescription,
            type: "article",
            siteName: "PC FIX",
        },
    };
}
export default async function ProblemPage({ params, }: PageProps) {
    const { slug } = await params;
    const problem = findProblemBySlug(slug);
    if (!problem) {
        notFound();
    }
    const relatedProblems = problem.relatedSlugs
        .map(findProblemBySlug)
        .filter((item): item is Problem => Boolean(item));
    const faq = problem.faqs;
    const baseUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://pcfixbase.com").replace(/\/$/, "");
    const relatedErrors = errorCodes.filter(entry => entry.relatedProblemSlugs.includes(problem.slug)).slice(0, 6);
    const breadcrumbJsonLd = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: [
            {
                "@type": "ListItem",
                position: 1,
                name: "PC FIX",
                item: `${baseUrl}/zh-CN`,
            },
            {
                "@type": "ListItem",
                position: 2,
                name: problem.category,
                item: `${baseUrl}/zh-CN/category/${encodeURIComponent(problem.category)}`,
            },
            {
                "@type": "ListItem",
                position: 3,
                name: problem.title,
            },
        ],
    };
    const articleJsonLd = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        headline: problem.title,
        url: `${baseUrl}/zh-CN/problems/${problem.slug}`,
        inLanguage: "zh-CN",
        description: problem.seoDescription,
        about: problem.category,
        author: {
            "@type": "Organization",
            name: "PC FIX",
        },
        publisher: {
            "@type": "Organization",
            name: "PC FIX",
        },
    };
    const faqJsonLd = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faq.map((item) => ({
            "@type": "Question",
            name: item.question,
            acceptedAnswer: {
                "@type": "Answer",
                text: item.answer,
            },
        })),
    };
    return (<main className="relative min-h-screen bg-slate-50 text-slate-900">
      {/* JSON-LD */}

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(breadcrumbJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(articleJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <script type="application/ld+json" dangerouslySetInnerHTML={{
            __html: JSON.stringify(faqJsonLd).replace(/</g, "\\u003c"),
        }}/>

      <SiteHeader />

      <div className="mx-auto max-w-5xl px-5 py-8 sm:py-12">
        {/* Breadcrumb */}

        <nav className="mb-6 flex flex-wrap items-center gap-2 text-sm text-slate-500">
          <Link href="/zh-CN" className="transition hover:text-blue-600">
            PC FIX
          </Link>

          <span>›</span>

          <Link href={`/zh-CN/category/${encodeURIComponent(problem.category)}`} className="transition hover:text-blue-600">
            {problem.category}
          </Link>

          <span>›</span>

          <span className="text-slate-700">
            {problem.title}
          </span>
        </nav>

        {/* 문제 소개 */}

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
          <div className="mb-4">
            <span className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-sm font-semibold text-blue-700">
              {problem.category}
            </span>
          </div>

          <h1 className="text-3xl font-black leading-tight tracking-tight text-slate-950 sm:text-4xl">
            {problem.title}
          </h1>

          <p className="mt-4 max-w-3xl text-base leading-7 text-slate-600 sm:text-lg">
            {problem.description}
          </p>

          <div className="mt-6 rounded-xl border border-blue-100 bg-blue-50 p-4">
            <p className="text-sm leading-6 text-blue-900">
              <strong>{" \u6C42\u89E3\u987A\u5E8F "}</strong>

              <br />{" \u6211\u4EEC\u4ECE\u6700\u7B80\u5355\u3001\u6700\u4FBF\u5B9C\u7684\u65B9\u6CD5\u5F00\u59CB\u7EC4\u7EC7\u8FD9\u4E9B\u65B9\u6CD5\u3002\u8BF7\u4ECE\u4E0A\u5230\u4E0B\uFF0C\u4E00\u4E00\u68C0\u67E5\u89E3\u51B3\u65B9\u6848\u3002 "}</p>
          </div>
        </section>

        {/* 증상 + 원인 */}

        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-black text-slate-950">{" \u4F60\u6709\u8FD9\u4E9B\u75C7\u72B6\u5417\uFF1F "}</h2>

            <ul className="mt-5 space-y-3">
              {problem.symptoms.map((symptom, index) => (<li key={index} className="flex gap-3 text-sm leading-6 text-slate-700">
                    <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-blue-500"/>

                    <span>
                      {symptom}
                    </span>
                  </li>))}
            </ul>
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-black text-slate-950">{" \u4E3B\u8981\u539F\u56E0 "}</h2>

            <ul className="mt-5 space-y-3">
              {problem.causes.map((cause, index) => (<li key={index} className="flex gap-3 text-sm leading-6 text-slate-700">
                    <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-orange-500"/>

                    <span>
                      {cause}
                    </span>
                  </li>))}
            </ul>
          </section>
        </div>

        {/* 해결 방법 */}

        <section className="mt-10">
          <div>
            <h2 className="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{" \u5982\u4F55\u89E3\u51B3 "}</h2>

            <p className="mt-2 text-sm text-slate-500">{" \u8BF7\u4ECE\u4E0A\u5230\u4E0B\u6309\u987A\u5E8F\u68C0\u67E5\u3002\u5982\u679C\u95EE\u9898\u5DF2\u89E3\u51B3\uFF0C\u5219\u65E0\u9700\u7EE7\u7EED\u6267\u884C\u4E0B\u4E00\u6B65\u3002 "}</p>
          </div>

          <div className="mt-6 space-y-6">
            {problem.solutions.map((solution) => (<article key={solution.order} id={`solution-${solution.order}`} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                  <div className="border-b border-slate-100 bg-slate-50 px-5 py-5 sm:px-6">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                      <div className="flex gap-4">
                        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-black text-white">
                          {solution.order}
                        </div>

                        <div>
                          <h3 className="text-lg font-bold text-slate-950 sm:text-xl">
                            {solution.title}
                          </h3>

                          <p className="mt-2 text-sm leading-6 text-slate-600">
                            {solution.reason}
                          </p>
                        </div>
                      </div>

                      <div className="flex shrink-0 flex-wrap gap-2 text-xs font-semibold">
                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u96BE\u5EA6"}{" "}
                          {translate(solution.difficulty)}
                        </span>

                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u65F6\u95F4"}{" "}
                          {solution.time}
                        </span>

                        <span className="rounded-full bg-white px-3 py-1.5 text-slate-700 ring-1 ring-slate-200">{" \u6210\u672C"}{" "}
                          {solution.cost}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="px-5 py-6 sm:px-6">
                    <ol className="space-y-4">
                      {solution.steps.map((step, index) => (<li key={index} className="flex gap-3 text-sm leading-7 text-slate-700">
                            <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-slate-100 text-xs font-bold text-slate-600">
                              {index + 1}
                            </span>

                            <span>
                              {step}
                            </span>
                          </li>))}
                    </ol>

                    {solution.checkPoint && (<div className="mt-6 rounded-xl border border-green-200 bg-green-50 p-4">
                        <p className="text-sm font-bold text-green-800">{" \u786E\u8BA4\u70B9 "}</p>

                        <p className="mt-1 text-sm leading-6 text-green-700">
                          {solution.checkPoint}
                        </p>
                      </div>)}
                  </div>
                </article>))}
          </div>
        </section>

        {/* 주의사항 */}

        {problem.warning && (<section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6">
            <h2 className="text-lg font-black text-amber-900">{" \u6CE8\u610F\u4E8B\u9879 "}</h2>

            <p className="mt-2 text-sm leading-7 text-amber-800">
              {problem.warning}
            </p>
          </section>)}

        

        


    {/* 관련 문제 */}

        {relatedProblems.length > 0 && (<>
    {/* 관련 문제 위 여백 */}
    <div aria-hidden="true" style={{
                height: "96px",
            }}/>

    <section style={{
                borderTop: "1px solid #e2e8f0",
                paddingTop: "48px",
            }}>
      <div>
        <h2 className="text-2xl font-black text-slate-950">{" \u76F8\u5173\u95EE\u9898 "}</h2>

        <p className="mt-2 text-sm text-slate-500">{" \u5982\u679C\u75C7\u72B6\u4E0D\u5B8C\u5168\u5339\u914D\uFF0C\u8BF7\u68C0\u67E5\u4EE5\u4E0B\u95EE\u9898\u3002 "}</p>
      </div>

      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        {relatedProblems.map((relatedProblem) => (<Link key={relatedProblem.slug} href={`/zh-CN/problems/${relatedProblem.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
            <span className="text-xs font-bold text-blue-600">
              {relatedProblem.category}
            </span>

            <h3 className="mt-2 font-bold text-slate-950 group-hover:text-blue-600">
              {relatedProblem.title}
            </h3>

            <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">
              {relatedProblem.description}
            </p>

            <div className="mt-4 text-sm font-bold text-blue-600">{" \u67E5\u770B\u89E3\u51B3\u65B9\u6CD5 \u2192 "}</div>
          </Link>))}
      </div>
    </section>
  </>)}
        {relatedErrors.length > 0 && (<section className="mt-12">
            <h2 className="text-2xl font-black">{"\u76F8\u5173\u9519\u8BEF\u4EE3\u7801"}</h2>
            <p className="mt-2 text-sm text-slate-500">{"\u5982\u679C\u5C4F\u5E55\u4E0A\u51FA\u73B0\u4EE5\u4E0B\u4EE3\u7801\uFF0C\u8BF7\u53C2\u9605\u6BCF\u4E2A\u9519\u8BEF\u7684\u786E\u8BA4\u6B65\u9AA4\u3002"}</p>
            <div className="mt-6 grid gap-4 sm:grid-cols-2">{relatedErrors.map(entry => <ErrorCard key={entry.slug} entry={entry}/>)}</div>
            <Link href="/zh-CN/errors" className="mt-4 inline-block font-semibold text-blue-600">{"\u67E5\u770B\u6240\u6709\u9519\u8BEF\u4EE3\u7801 \u2192"}</Link>
          </section>)}
        {/* 하단 CTA */}

        <section className="mt-14 rounded-3xl bg-slate-900 p-7 text-white sm:p-9">
          <h2 className="text-2xl font-black">{" \u8FD8\u8981\u5BFB\u627E\u5176\u4ED6\u75C7\u72B6 "}</h2>

          <p className="mt-3 text-sm leading-6 text-slate-300">{" \u5982\u679C\u60A8\u5728 PC FIX \u641C\u7D22\u6846\u4E2D\u8F93\u5165\u60A8\u5F53\u524D\u770B\u5230\u7684\u75C7\u72B6\uFF0C\u6211\u4EEC\u5C06\u627E\u5230\u76F8\u5173\u95EE\u9898\u3002 "}</p>

          <Link href="/zh-CN" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900 transition hover:bg-slate-100">{" \u641C\u7D22\u5176\u4ED6\u95EE\u9898 \u2192 "}</Link>
        </section>
      <section className="mt-16">
          <div>
            <h2 className="text-2xl font-black text-slate-950">{" \u5E38\u89C1\u95EE\u9898\u89E3\u7B54 "}</h2>

            <p className="mt-2 text-sm text-slate-500">{" \u6211\u4EEC\u5217\u51FA\u4E86\u6211\u4EEC\u7ECF\u5E38\u68C0\u67E5\u7684\u6709\u5173\u6B64\u95EE\u9898\u7684\u4E8B\u9879\u5217\u8868\u3002 "}</p>
          </div>

          <div className="mt-6 space-y-4">
            {faq.map((item, index) => (<FaqItem key={index} question={item.question} answer={item.answer}/>))}
          </div>
        </section>
      </div>

      <div className="display-ad-sides"><DisplayAd label="广告" placement="left" /><DisplayAd label="广告" placement="right" /></div><DisplayAd label="广告" /><SiteFooter />
    </main>);
}
